extends:
  - 'stylelint-config-recommended'
  - 'stylelint-config-standard'
  - 'stylelint-config-prettier'
rules:
  rule-empty-line-before: always
  block-opening-brace-newline-after: always
  block-closing-brace-newline-before: always
  declaration-colon-space-after: always-single-line
  declaration-colon-newline-after: always-multi-line
  declaration-block-trailing-semicolon: always
  no-extra-semicolons: true
  declaration-block-semicolon-newline-after: always
  declaration-block-no-redundant-longhand-properties: true
  indentation: 2
  max-line-length: 80
  no-empty-first-line: true